# Generated by Django 5.1.1 on 2024-10-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_de_tarefa', '0004_alter_task_atribuida_a_alter_task_data_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='atribuida_a',
            new_name='usuario',
        ),
    ]
