# Generated by Django 5.1.1 on 2024-10-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_de_tarefa', '0007_alter_task_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
