# Generated by Django 5.1.1 on 2024-11-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_de_tarefa', '0008_alter_task_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
